- ButcherMod/common/DataLoader.cs
- ButcherMod/manifest.json
- Fix insemination syringe not working when meat is disabled.
> Animal Husbandry Mod 2.4.0

- CustomKissingMod/CustomKissingModEntry.cs
- CustomKissingMod/DataLoader.cs
- CustomKissingMod/ModConfig.cs
- CustomKissingMod/NPCOverrides.cs
- CustomKissingMod/NpcConfig.cs
- CustomKissingMod/Properties/AssemblyInfo.cs
- CustomKissingMod/i18n/default.json
- CustomKissingMod/i18n/pt.json
- CustomKissingMod/manifest.json
- CustomKissingMod/packages.config
- StardewValleyMods.sln
> Custom Kissing Mod 1.0.0

- CustomCaskMod/CaskOverrides.cs
- CustomCaskMod/CustomCaskMod.csproj
- CustomCaskMod/CustomCaskModEntry.cs
- CustomCaskMod/DataLoader.cs
- CustomCaskMod/contentPackTemplate/CaskData.json
- CustomCaskMod/contentPackTemplate/manifest.json
- CustomCaskMod/manifest.json
- Adds content pack.
- Adds configuration by object name.
> Custom Cask Mod 1.2.0

- CustomProducerMod/ProducerRules.json
- CustomProducerMod/ProducersConfig.json
- CustomProducerMod/Properties/AssemblyInfo.cs
- CustomProducerMod/[PFM]CustomProducerMod.csproj
- CustomProducerMod/manifest.json
- CustomProducerMod/packages.config
- StardewValleyMods.sln
- Adding all vanilla machines currently supported by Producer Framework Mod.
> Custom Producer Mod 1.0.0

- PFMAutomate/manifest.json
- Forgot to commit the nexus id.
> PFMAutomate 1.0.0

- PFMAutomate/PFMAutomateModEntry.cs
- PFMAutomate/manifest.json
- Fix for the Automate patch for vanilla machines to work even when SMAPI recompile the code.
> PFMAutomate 1.0.1

- ProducerFrameworkMod/ContentPack/LightSourceConfig.cs
- ProducerFrameworkMod/ContentPackTemplate/ProducersConfig.json
- ProducerFrameworkMod/ObjectOverrides.cs
- ProducerFrameworkMod/manifest.json
- Fix to light source always being lit.
- New property to configure the light source to always be lit.
> Producer Framework Mod 1.3.1

- ProducerFrameworkMod/ContentPackTemplate/ProducersConfig.json
- ProducerFrameworkMod/OutputConfigController.cs
- ProducerFrameworkMod/ProducerRuleController.cs
- ProducerFrameworkMod/manifest.json
- Fix to multiplayer not being applied to the price of the output object.
- Improvement to the random calculation.
- Fixes to the template.
> Producer Framework Mod 1.3.2

- CustomProducerMod/ProducerRules.json
- CustomProducerMod/ProducersConfig.json
- CustomProducerMod/manifest.json
- Adding Worm Bin, Soda Machine, Statue of Perfection and Mushroom Box
- Adding light source to the furnace
- Adding status to keg, preserve jar and cheese press
> Custom Producer Mod 1.1.0

- CustomProducerMod/ProducerRules.json
- CustomProducerMod/manifest.json
- Fix to Aged Roe color property.
> Custom Producer Mod 1.2.1

- PFMAutomate/manifest.json
- Manifest edition after recompilation for release.
> PFMAutomate 1.2.1

- ProducerFrameworkMod/ObjectOverrides.cs
- ProducerFrameworkMod/ProducerFrameworkMod.csproj
- ProducerFrameworkMod/i18n/de.json
- ProducerFrameworkMod/manifest.json
- Fix to bee house to work indoors.
- Deutsch i18n
> Producer Framework Mod 1.4.1

- ButcherMod/manifest.json
> Animal Husbandry Mod 2.5.0-beta1

- CustomCaskMod/CaskOverrides.cs
- CustomCaskMod/CustomCaskModEntry.cs
- CustomCaskMod/ModConfig.cs
- CustomCaskMod/manifest.json
- Removing patch to automate
- Changing methods patched since there are now better methods to patch to archive the same goal.
- Config option to make the mod work with the new logic of increasing quality.
> Custom Cask Mod 1.2.2

- PFMAutomate/Automate/CustomProducerMachine.cs
- PFMAutomate/Automate/ProducerFrameworkAutomationFactory.cs
- PFMAutomate/AutomateOverrides.cs
- PFMAutomate/manifest.json
> PFMAutomate 1.2.2

- PFMAutomate/Automate/CustomProducerMachine.cs
- PFMAutomate/manifest.json
- update to support PFM 1.5.0
- Season now consider the location of the machine.
> PFMAutomate 1.2.3

- MailFrameworkMod/ContentPack/Attachment.cs
- MailFrameworkMod/ContentPack/ItemType.cs
- MailFrameworkMod/ContentPackTemplate/mail.json
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/manifest.json
- Support for Furniture, Weapons and Boots as attachments.
- New property to set the upgrade level of attached tools.
> Mail Framework Mod 1.8.0

- MailFrameworkMod/MailController.cs
- MailFrameworkMod/MailFrameworkModEntry.cs
- MailFrameworkMod/manifest.json
- Removing old unused methods
- Changing event monitor of closing menu to be a callback function from the vanilla game.
- Changing controller to handler screens individually, and avoid conflicts between players.
- Adding a failsafe code for when the game remove the letter screen without closing it. Leaving the mod thinking the letter is still open.
> Mail Framework Mod 1.8.1

- MailFrameworkMod/Letter.cs
- MailFrameworkMod/MailController.cs
- MailFrameworkMod/MailFrameworkMod.csproj
- MailFrameworkMod/manifest.json
- New option to add dynamic items to the letter
- New method to remove a letter from the mailbox
- Updating Pathoschild.Stardew.ModBuildConfig to 3.2.2
> Mail Framework Mod 1.9.0

- MailServicesMod/DataLoader.cs
- MailServicesMod/MailServicesMod.csproj
- MailServicesMod/MailServicesModEntry.cs
- MailServicesMod/Properties/launchSettings.json
- MailServicesMod/ToolUpgradeOverrides.cs
- MailServicesMod/i18n/default.json
- MailServicesMod/i18n/ko.json
- MailServicesMod/i18n/pt.json
- MailServicesMod/manifest.json
- StardewValleyMods.sln
- Receive upgraded tool in the mail.
- Don't let Trash Cans be picked up from letters.
- Remove upgrade letter if the player go get it in the blacksmith.
- Add tool to upgrade using the mail box.
- Messages if the player don't have enough money or metal bars.
- Message if the player successfully sent the letter.
> Mail Services Mod 1.0.0

- MailServicesMod/DataLoader.cs
- MailServicesMod/ItemShipmentQuestOverrides.cs
- MailServicesMod/MailServicesModEntry.cs
- MailServicesMod/ModConfig.cs
- MailServicesMod/i18n/default.json
- MailServicesMod/i18n/ko.json
- MailServicesMod/i18n/pt.json
- MailServicesMod/manifest.json
- New feature to finish item delivery quest and lost item quests using the mailbox
- New config file with option to show delivery quest dialog on shipment
- New letter to explain the quest feature
> Mail Services Mod 1.1.0

- MailFrameworkMod/MailController.cs
- MailFrameworkMod/manifest.json
- Fix bug were custom letters would not open and be removed from the mailbox if the player was holding an object.
> Mail Framework Mod 1.9.1

- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/LetterViewerMenuExtended.cs
- MailFrameworkMod/manifest.json
- Optimization for assets loading from content packs. Should only load on instance of an asset.
- Fix to callback of letters not being called if an menu was opened to add an item to the inventory.
> Mail Framework Mod 1.9.2

- MailServicesMod/GiftShipmentController.cs
- MailServicesMod/ModConfig.cs
> Mail Services Mod 1.3.1

- ButcherMod/AnimalHusbandryModEntry.cs
- ButcherMod/common/TvOverrides.cs
- ButcherMod/manifest.json
- ButcherMod/tools/FeedingBasketOverrides.cs
- ButcherMod/tools/InseminationSyringeOverrides.cs
- ButcherMod/tools/MeatCleaverOverrides.cs
- ButcherMod/tools/ParticipantRibbonOverrides.cs
- Fixing TV channel not working when PyTK loads custom channels.
- Changes to tool attachment and verification to try to fix MacOS compatibility.
> Animal Husbandry Mod 2.5.0-beta5

- CustomCrystalariumMod/ObjectOverrides.cs
- CustomCrystalariumMod/manifest.json
- Fix Custom Cloners starting just for hovering the mouse over it.
- Fixed Custom Cloners defined by category not setting MinutesUntilReady
- Adding support to light source for cloners.
> Custom Crystalarium Mod 1.2.1

- PFMAutomate/PFMAutomateModEntry.cs
- PFMAutomate/manifest.json
- Fix to work without CCRM installed.
> PFMAutomate 1.4.1

- MailServicesMod/ConfigMenuController.cs
- MailServicesMod/DataLoader.cs
- MailServicesMod/GiftShipmentController.cs
- MailServicesMod/GiftShipmentOverrides.cs
- MailServicesMod/ItemShipmentQuestOverrides.cs
- MailServicesMod/MailServicesModEntry.cs
- MailServicesMod/ModConfig.cs
- MailServicesMod/ToolUpgradeOverrides.cs
- MailServicesMod/i18n/default.json
- MailServicesMod/i18n/ko.json
- MailServicesMod/i18n/pt.json
- MailServicesMod/i18n/tr.json
- MailServicesMod/integrations/GenericModConfigMenuApi.cs
- MailServicesMod/manifest.json
- New properties for shipment fee. Gift, tool and quest.
- New messager for no money.
- New manifest description
- New config menu using Generic Mod Config Menu integration
- Recreating the menu when a new farmer config is created.
- Turkish translation
> Mail Services Mod 1.4.0

- MailFrameworkMod/ContentPack/Collection.cs
- MailFrameworkMod/ContentPackTemplate/mail.json
- MailFrameworkMod/ContentPackTemplate/manifest.json
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/MailController.cs
- MailFrameworkMod/manifest.json
- Fix to no text letters with i18n files breaking.
- Fix to letter from content pack not loading after one collection condition warning.
- Adding new collection requirement type for crafting recipes.
> Mail Framework Mod 1.10.1

- ProducerFrameworkMod/Utils/ObjectTranslationExtension.cs
- ProducerFrameworkMod/manifest.json
- Fixing custom output names not working when there is now i18n file.
> Producer Framework Mod 1.7.1

- ProducerFrameworkMod/Controllers/OutputConfigController.cs
- ProducerFrameworkMod/ProducerFrameworkMod.csproj
- ProducerFrameworkMod/i18n/hu.json
- ProducerFrameworkMod/manifest.json
- Hungarian Translation
- Fix to Preserved Type outputs not using the right name when KeepInputParentIndex was true.
> Producer Framework Mof 1.7.3

- MailFrameworkMod/ContentPack/MailItem.cs
- MailFrameworkMod/ContentPackTemplate/mail.json
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/MailFrameworkModEntry.cs
- MailFrameworkMod/integrations/IConditionsChecker.cs
- MailFrameworkMod/manifest.json
- New properties to make it possible to use Expanded Preconditions.
- New property to add additional "mail received" on reading the letter.
> Mail Framework Mod 1.12.0

- MailFrameworkMod/ContentPack/MailItem.cs
- MailFrameworkMod/ContentPackTemplate/mail.json
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/MailFrameworkMod.csproj
- MailFrameworkMod/manifest.json
- Upgrade to be compatible with Stardew Valley 1.5.5
- New property for required farm house level.
> Mail Framework Mod 1.12.2

- ButcherMod/animals/AnimalContestEventBuilder.cs
- ButcherMod/animals/AnimalExtension.cs
- ButcherMod/animals/data/AnimalData.cs
- ButcherMod/common/DataLoader.cs
- ButcherMod/manifest.json
- ButcherMod/tools/InseminationSyringeOverrides.cs
- Fix to Ostrich and Golden Chiken generating custom animals config.
- Custom Animal configuration won't work if they have the same name as a vanilla animal.
- Trace log for animal contest event, to help debug event errors.
- Fix a freeze bug when trying to inseminate an Ostrich.
> Animal Husbandry Mod 2.6.1

- MailFrameworkMod/Commands.cs
- MailFrameworkMod/ContentPack/MailItem.cs
- MailFrameworkMod/ContentPackTemplate/mail.json
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/MailController.cs
- MailFrameworkMod/MailFrameworkModEntry.cs
- MailFrameworkMod/manifest.json
- Update to make it compatible with SMAPI 4
- Log typo fixes
- New console command to help debug player mailbox
- New property to check mine level
- New property to check current money
- New property to check total money earned
- Letter collection menu now show appropriated close button.
> Mail Framework Mod 1.13.0

- CCRMAutomate/Automate/ClonerMachine.cs
- CCRMAutomate/CCRMAutomate.csproj
- CCRMAutomate/CCRMAutomateModEntry.cs
- CCRMAutomate/ModConfig.cs
- CCRMAutomate/manifest.json
- Updating mod to Stardew Valley 1.5.5
- Making mod compatible with SMAPI 4
- New config property to let cloners be started with automate
> CCRMAutomate 1.1.0

- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/Letter.cs
- MailFrameworkMod/MailController.cs
- MailFrameworkMod/manifest.json
- More refactoring to support SMAPI 4
- Letter now can store ITranslationHelper, to dynamically translate letters.
- Content packs letters now are loaded with dynamic translations.
> Mail Framework Mod 1.14.0

- MailFrameworkMod/Api/ApiLetter.cs
- MailFrameworkMod/Api/ILetter.cs
- MailFrameworkMod/Api/IMailFrameworkModApi.cs
- MailFrameworkMod/Api/MailFrameworkModApi.cs
- MailFrameworkMod/ContentPack/ContentPackComparer.cs
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/Letter.cs
- MailFrameworkMod/MailController.cs
- MailFrameworkMod/MailDao.cs
- MailFrameworkMod/MailFrameworkMod.csproj
- MailFrameworkMod/MailFrameworkModEntry.cs
- MailFrameworkMod/manifest.json
- Upgrade to ModBuildConfig 4.1.0
- New error handler for the letter flow, to avoid error when executing letter dynamic items and callback code.
- Letters now have a method to generate MailData String.
- New API for integration with Mail Framework Mod
- API method to direct load a content pack from a SMAPI mod.
- API method to load a letter from an ILetter object.
- API method to return a ILetter from an ID.
- API method to return the MailData string of a letter identified per ID.
> Mail Framework Mod 1.15.0

- BorderlessWoodFloorMod/BorderlessWoodFloorMod.csproj
- BorderlessWoodFloorMod/BorderlessWoodFloorModEntry.cs
- BorderlessWoodFloorMod/DataLoader.cs
- BorderlessWoodFloorMod/manifest.json
- Update to SMAPI 4.0
- Update to Stardew Valley 1.5.5
> Borderless Wood Floor Mod 1.0.1

- AdvancedCasksMod/[JA]AdvancedCasksMod/BigCraftables/Hardwood Cask/big-craftable.json
- AdvancedCasksMod/[JA]AdvancedCasksMod/BigCraftables/Radioactive Cask/big-craftable.json
- AdvancedCasksMod/manifest.json
- File changes that were missing last commit but were in the release.
> Advanced Casks Mod 1.0.2

- CustomCrystalariumMod/ObjectOverrides.cs
- CustomCrystalariumMod/manifest.json
- Fix to logging erro in the game loop when PerformToolAction is called with Tool property null.
> Custom Crystalarium Mod 1.4.1

- CustomCrystalariumMod/ObjectOverrides.cs
- CustomCrystalariumMod/manifest.json
- Fix not using the default cloning time when refeshing the cloner.
> Custom Crystalarium Mod 1.4.2

- MailFrameworkMod/MailController.cs
- MailFrameworkMod/manifest.json
> Mail Framework Mod 1.16.0

- MailServicesMod/ToolUpgradeController.cs
- MailServicesMod/manifest.json
- Creating new upgraded tool from the QualifiedItemId in the stock information.
> Mail Services Mod 1.5.1

- ButcherMod/manifest.json
- ButcherMod/tools/ToolsFactory.cs
- ButcherMod/tools/ToolsLoader.cs
- Setting the display name and description to the ToolData of all custom tools to avoid null pointer from other mods.
- Setting ModData to ToolData, so tools created by other mods can work properly.
> Animal Husbandry Mod 2.6.3

- ButcherMod/ModConfig.cs
- ButcherMod/animals/AnimalQueryMenuExtended.cs
- ButcherMod/common/DataLoader.cs
- ButcherMod/manifest.json
- New property to disable the meat button
- Fix to Generic Mod Config Menu version.
> Animal Husbandry Mod 2.6.4

- CustomCaskMod/DataLoader.cs
- CustomCaskMod/manifest.json
- Fix OutputMethod format.
- Fix to Item Qualified Id not being used when ageable were set by name.
> Custom Cask Mod 1.6.0

- ButcherMod/AnimalHusbandryModEntry.cs
- ButcherMod/animals/LivingWithTheAnimalsChannel.cs
- ButcherMod/common/Channel.cs
- ButcherMod/common/DataLoader.cs
- ButcherMod/common/EventsLoader.cs
- ButcherMod/common/TvController.cs
- ButcherMod/cooking/CookingExtension.cs
- ButcherMod/manifest.json
- ButcherMod/recipes/MeatFridayChannel.cs
- ButcherMod/recipes/RecipesLoader.cs
- Multiple fixes to language not being loaded
- Fix to event not playing on languages other than default
- Fix to all recipes bean learned by default.
> Animal Husbandry Mod 2.6.5

- ButcherMod/AnimalHusbandryModEntry.cs
- ButcherMod/common/DataLoader.cs
- ButcherMod/integrations/GenericModConfigMenuApi.cs
- ButcherMod/manifest.json
- ButcherMod/tools/ToolOverridesBase.cs
- Removing test command.
- Removing temporary fix for tools not being added to the inventory from the letter.
- Fix to cooking recipes not being loaded for some user.
- Possible fix to null pointer when creating custom animals template
- Updating to GenericModConfigMenuApi
- Making BaseToolDoFunction null safe.
> Animal Husbandry Mod 2.6.7

- ProducerFrameworkMod/ContentPackTemplate/ProducerRules.json
- ProducerFrameworkMod/Controllers/OutputConfigController.cs
- ProducerFrameworkMod/Controllers/ProducerRuleController.cs
- ProducerFrameworkMod/Utils/ObjectUtils.cs
- ProducerFrameworkMod/manifest.json
- Fix to Prices multiplier and increment not being done properly because of some compilation bug.
- Resetting lastOutputRuleId to avoid future problem.
- Adding support to new PreserveTypes.
> Producer Framework Mod 1.8.0

- MailServicesMod/NpcUtility.cs
- MailServicesMod/manifest.json
- Capatibility with Stardew Valley 1.6.3
> Mail Services Mod 1.5.3

- ButcherMod/animals/FarmAnimalOverrides.cs
- ButcherMod/common/DataLoader.cs
- ButcherMod/manifest.json
- Fix product bonus transpiler
- Trying to fix null reference exception when creating animal template.
> Animal Husbandry Mod 2.6.9

- ProducerFrameworkMod/ObjectOverrides.cs
- ProducerFrameworkMod/manifest.json
- Passing texture for getSourceRectForBigCraftable, so it can calculate the frames properly.
> Producer Framework Mod 1.9.1

- MailFrameworkMod/MailController.cs
- MailFrameworkMod/manifest.json
- Fix to recipe translated name.
> Mail Framework Mod 1.16.1

- ProducerFrameworkMod/Controllers/OutputConfigController.cs
- ProducerFrameworkMod/Controllers/ProducerController.cs
- ProducerFrameworkMod/Controllers/ProducerRuleController.cs
- ProducerFrameworkMod/ObjectOverrides.cs
- ProducerFrameworkMod/Utils/SoundUtil.cs
- ProducerFrameworkMod/manifest.json
- Fix to not consuming fairy dust item when using on machines.
- Fix warnings when producing colored objects and torches.
- Possible fix to improper sounds when automating.
> Producer Framework Mod 1.9.2

- MailFrameworkMod/ContentPack/CollectionCondition.cs
- MailFrameworkMod/ContentPack/MailItem.cs
- MailFrameworkMod/ContentPack/ReplyConfig.cs
- MailFrameworkMod/ContentPack/ReplyOption.cs
- MailFrameworkMod/ContentPackTemplate/mail.json
- MailFrameworkMod/DataLoader.cs
- MailFrameworkMod/MailFrameworkModEntry.cs
- MailFrameworkMod/ReplyController.cs
- MailFrameworkMod/ReplyRepository.cs
- MailFrameworkMod/manifest.json
- New Ids property to replace Index and Name for CollectionConditions. It will aggregate multiple items and sum their value to compare against the amount.
- Refactoring the attachment logic to a method.
- Fix to letter with recipe not supporting CustomTextColorName property.
- New ReplyConfig property to add a reply behavior.
- Fix null reference exception when an item with null name was present.
> Mail Framework Mod 1.18.0

- CustomCaskMod/CaskOverrides.cs
- CustomCaskMod/DataLoader.cs
- CustomCaskMod/ModConfig.cs
- CustomCaskMod/manifest.json
- Fix null reference exception when the game have a object with null name loaded.
- New config property to enable to age every custom ager anywhere.
> Custom Cask Mod 1.6.2

- CustomCaskMod/DataLoader.cs
- CustomCaskMod/manifest.json
- WaterRetainingFieldMod/HoeDirtOverrides.cs
- WaterRetainingFieldMod/WaterRetainingFieldMod.csproj
- WaterRetainingFieldMod/manifest.json
- Update for Stardew Valey 1.6
- Update to .net 6
> Water Retaining Field Mod 1.1.1

- CropTransplantMod/CropTransplantMod.csproj
- CropTransplantMod/CropTransplantModEntry.cs
- CropTransplantMod/DataLoader.cs
- CropTransplantMod/HeldIndoorPot.cs
- CropTransplantMod/TransplantController.cs
- CropTransplantMod/TransplantOverrides.cs
- CropTransplantMod/TreeExtension.cs
- CropTransplantMod/integrations/ApiLetter.cs
- CropTransplantMod/integrations/GenericModConfigMenuApi.cs
- CropTransplantMod/integrations/ILetter.cs
- CropTransplantMod/integrations/IMailFrameworkModApi.cs
- CropTransplantMod/manifest.json
- StardewValleyMods.sln
- Changing to .net6
- Updating logic to SV 1.6
- Removing MFM dependency.
- Adding letter using MFM API.
- Update to new GMCM api.
- Loading mail on save loaded to apply language changes.
> Crop Transplant Mod 1.3.2

- ButcherMod/AnimalHusbandryModEntry.cs
- ButcherMod/common/DataLoader.cs
- ButcherMod/common/EventsLoader.cs
- ButcherMod/manifest.json
- ButcherMod/meats/MeatOverrides.cs
- ButcherMod/recipes/RecipesLoader.cs
- ButcherMod/tools/InseminationSyringeOverrides.cs
- ButcherMod/tools/ToolsLoader.cs
- Reading the Queen of Sauce Book will also teach you the meat Friday recipes.
- Fix bug where liked treats were not loaded if you had meat disabled.
- Cashes are now invalidated if you change the config in game.
- Fix game breaking bug when using the syringe on blue chickens.
- Lots of improvements related to loading assets order and config properties.
> Animal Husbandry Mod 2.6.12

- MailServicesMod/ConfigMenuController.cs
- MailServicesMod/MailServicesMod.csproj
- MailServicesMod/Properties/launchSettings.json
- MailServicesMod/ToolUpgradeOverrides.cs
- MailServicesMod/integrations/GenericModConfigMenuApi.cs
- MailServicesMod/manifest.json
- Update to GMCM new api.
- Fix GMCM reset button not working.
- Tool upgrade now accept any tool Clint can upgrade. Should work with tools from other mods if they were added properly.
> Mail Services Mod 1.6.0

- ButcherMod/animals/AnimalContestEventBuilder.cs
- ButcherMod/common/EventsLoader.cs
- ButcherMod/manifest.json
- Fix animal contest not loading the event even when enabled
- Change event condition to season command instead of not season command
> Animal Husbandry Mod 2.6.13

- AdvancedWeatherForecastMod/common/DataLoader.cs
- AdvancedWeatherForecastMod/common/ModConfig.cs
- AdvancedWeatherForecastMod/i18n/default.json
- AdvancedWeatherForecastMod/i18n/pt.json
- AdvancedWeatherForecastMod/i18n/tr.json
- AdvancedWeatherForecastMod/i18n/zh.json
- AdvancedWeatherForecastMod/manifest.json
- AdvancedWeatherForecastMod/overrides/LocationWeatherOverrides.cs
- Fix error when creating a new game.
- Added a config property to disable the letter explaining the forecast.
- Turkish  i18n.
- Chinese i18n update.
> Advanced Weather Forecast Mod 1.1.1

- ProducerFrameworkMod/ProducerFrameworkMod.csproj
- ProducerFrameworkMod/manifest.json
- Fix when input was not an object or machine was invisible, it would not let any other mod patch work.
> Producer Framework Mod 1.9.7

- CustomKissingMod/ConfigMenuController.cs
- CustomKissingMod/CustomKissingMod.csproj
- CustomKissingMod/ModConfig.cs
- CustomKissingMod/NPCOverrides.cs
- CustomKissingMod/i18n/default.json
- CustomKissingMod/i18n/pt.json
- CustomKissingMod/manifest.json
- New property to disable the cursor indication when you can kiss a NPC.
- Fix error on Unix systems because of the case of the beach sprite file.
> Custom Kissing Mod 1.3.1
