ButcherMod/AnimalHusbandryMod.csproj, ButcherMod/AnimalHusbandryModEntry.cs, ButcherMod/animals/PregnancyController.cs, ButcherMod/common/DataLoader.cs, ButcherMod/recipes/RecipesLoader.cs, ButcherMod/tools/FeedingBasket.cs, ButcherMod/tools/ToolsLoader.cs, CropTransplantMod/CropTransplantModEntry.cs, CustomCaskMod/CustomCaskModEntry.cs, CustomCrystalariumMod/CustomCrystalariumModEntry.cs, EverlastingBaitsUnbreakableTacklesMod/Commands.cs, EverlastingBaitsUnbreakableTacklesMod/EverlastingBaitsAndUnbreakableTacklesMod.csproj, EverlastingBaitsUnbreakableTacklesMod/EverlastingBaitsAndUnbreakableTacklesModEntry.cs, MailFrameworkMod/Commands.cs, MailFrameworkMod/LetterViewerMenuExtended.cs, MailFrameworkMod/MailController.cs, MailFrameworkMod/MailDao.cs, MailFrameworkMod/MailFrameworkMod.csproj, MailFrameworkMod/MailFrameworkModEntry.cs, WaterRetainingFieldMod/WaterRetainingFieldModEntry.cs
SMAPI 3.0 will load mods much earlier, so `Entry` will be called before the game is fully initialised. This PR updates the code to handle that (should work fine in 2.11 too).
Changes in this pull request:
* Updated for SMAPI 3.0 loading mods earlier.
* Simplified Harmony patching code, and made it easier to detect breaking game changes (e.g. using `nameof` where possible so compile fails if the method is renamed).
* Fixed two typos (_Entery_ → _Entry_, and _Erro_ → _Error_).
Let me know if you want me to change anything!
=> Update for SMAPI 3.0 changes

ButcherMod/AnimalHusbandryModEntry.cs, ButcherMod/animals/AnimalContestController.cs, ButcherMod/animals/PetOverrides.cs, ButcherMod/common/EventOverrides.cs, ButcherMod/manifest.json
- Fix to Pets not working in the contest.
- Fix to Pets not being properly invisible before going to the contest.
- Fix to error in the log when skipping certain events.
=> Animal Husbandry 2.4.2-beta3

MailFrameworkMod/ContentPack/ItemType.cs, MailFrameworkMod/ContentPack/MailItem.cs, MailFrameworkMod/ContentPackTemplate/mail.json, MailFrameworkMod/DataLoader.cs, MailFrameworkMod/Letter.cs, MailFrameworkMod/LetterViewerMenuExtended.cs, MailFrameworkMod/MailController.cs, MailFrameworkMod/MailDao.cs, MailFrameworkMod/MailFrameworkModEntry.cs, MailFrameworkMod/manifest.json
Mail Framework Mod - 1.5.0
- Letter can now have Title and GroupId.
- Letter with Title are loaded in the game mail data, using the new game syntax for titles.
- Letter with the same group id are grouped when validating and only the first one is sent.
- Content Pack now have a Random Chance condition. It creates a seed based on the game day, game unique id and letter unique id, to avoid cheating.
- Removing Reelection for letter texture now that it's public.
- Letter can now be opened in the Collection Page, with their custom texture and text color.
- Keeping track of mail repository changes to correctly update mail data.
- Invalidate cache of mail in the begin of the day if Letter repository has changed.
- BigObject should now be BigCraftable. Both are accepted for now.
- Template …
=> Mail Framework Mod - 1.5.1

ButcherMod/AnimalHusbandryModEntry.cs, ButcherMod/animals/FarmAnimalOverrides.cs, ButcherMod/common/DataLoader.cs, ButcherMod/manifest.json
- Fix to fertility bonus with auto-grabber in the coop.
- The fix is done by checking if there is a object in the animal position to avoid error. The case where it was placed inside the auto-grabber is handled by a transpiler code that set the stack of the object being added to two.
- Better error handling of content pack loading.
=> Animal Husbandry Mod 2.4.2-beta6

ProducerFrameworkMod/Api/ProducerFrameworkModApi.cs, ProducerFrameworkMod/ContentPack/ProducerConfig.cs, ProducerFrameworkMod/ContentPackTemplate/ProducerRules.json, ProducerFrameworkMod/Controllers/AnimationController.cs, ProducerFrameworkMod/Controllers/LightSourceConfigController.cs, ProducerFrameworkMod/Controllers/OutputConfigController.cs, ProducerFrameworkMod/Controllers/ProducerController.cs, ProducerFrameworkMod/Controllers/ProducerRuleController.cs, ProducerFrameworkMod/Controllers/StatsController.cs, ProducerFrameworkMod/DataLoader.cs, ProducerFrameworkMod/ObjectOverrides.cs, ProducerFrameworkMod/ProducerFrameworkMod.csproj, ProducerFrameworkMod/ProducerFrameworkModEntry.cs, ProducerFrameworkMod/Utils/GameUtils.cs, ProducerFrameworkMod/Utils/NameUtils.cs, ProducerFrameworkMod/Utils/ObjectUtils.cs, ProducerFrameworkMod/Utils/SoundUtil.cs, ProducerFrameworkMod/manifest.json
- Loading ProducersConfig on mod loading to avoid light source not being created when loading the fist save.
- Fix to draw transpiler. The point of identification got a similar call after 1.5, so a change was needed to patch the right place.
- Checking for producing conditions when drawing animation.
- Fix to the way SubtractTimeOfDay was working. It was not converting string time to minutes, and not adjusting for the day starting time.
- Changing or namespace to better organize classes.
- Won't check for location condition on draw cycle, since location can't change after the producing has started.
=> Producer Framework Mod 1.4.2

CustomProducerMod/ProducerRules.json, CustomProducerMod/manifest.json
- update to support PFM 1.4.2
- fix time to complete for machines that subtract time of the day, considering the fixed logic of PFM.
=> Custom Producer Mod 1.2.2

BorderlessWoodFloorMod/BorderlessWoodFloorMod.csproj, ButcherMod/AnimalHusbandryMod.csproj, CropTransplantMod/CropTransplantMod.csproj, CustomCaskMod/CustomCaskMod.csproj, CustomCrystalariumMod/CustomCrystalariumMod.csproj, CustomKissingMod/CustomKissingMod.csproj, EverlastingBaitsUnbreakableTacklesMod/EverlastingBaitsAndUnbreakableTacklesMod.csproj, MailFrameworkMod/MailFrameworkMod.csproj, PFMAutomate/PFMAutomate.csproj, ProducerFrameworkMod/Api/IProducerFrameworkModAPI.cs, ProducerFrameworkMod/Api/ProducerFrameworkModApi.cs, ProducerFrameworkMod/ContentPack/ManifestData.cs, ProducerFrameworkMod/DataLoader.cs, ProducerFrameworkMod/ProducerFrameworkMod.csproj, WaterRetainingFieldMod/WaterRetainingFieldMod.csproj
This method is based on a similar one available JsonAssets, which allows compiled mods to directly add a content pack. This allows for mods to dynamically create producers and rules at start-up (writing them out to a temp directory) and load them directly into PFM.
I also updated the csproj files to use the <EnableHarmony> tags available in recent versions of SMAPI, as well as removing some hard-coded references which caused me some problems when initially loading the solution.
=> Add API method to allow mods to directly add content packs

MailFrameworkMod/ContentPack/MailItem.cs, MailFrameworkMod/ContentPackTemplate/mail.json, MailFrameworkMod/DataLoader.cs, MailFrameworkMod/Letter.cs, MailFrameworkMod/LetterViewerMenuExtended.cs, MailFrameworkMod/MailController.cs, MailFrameworkMod/MailFrameworkModEntry.cs, MailFrameworkMod/manifest.json
- Support to all vanilla tools
- Support to Slingshots as weapons
- Log when an invalid attachment type is used
- Auto open property to learn the recipe and call the callback function without placing the letter in the mailbox
- Validation to ignore null attachments.
- Refectory to remove reflection from LetterViewerMenuExtended since the properties and methods used are now public.
=> Mail Framework Mod 1.10.0

MailFrameworkMod/MailController.cs, MailFrameworkMod/manifest.json
- Fix to null cooking recipe names because JA is adding a "/null" at the end of English recipes, that shouldn't be there.
=> Mail Framework Mod 1.10.2

ProducerFrameworkMod/Controllers/OutputConfigController.cs, ProducerFrameworkMod/Utils/ObjectTranslationExtension.cs, ProducerFrameworkMod/manifest.json
- Fixing to only adding translation keys to an object if there is a OutputName defined. This way JA translation can work when there is no configuration for names in PFM.
- Fix to add the OutputName, and not the translated name when there is no translation key.
=> Producer Framework Mod 1.7.2

CustomCrystalariumMod/ClonerController.cs, CustomCrystalariumMod/CustomCloner.cs, CustomCrystalariumMod/CustomCrystalariumMod.csproj, CustomCrystalariumMod/CustomCrystalariumModEntry.cs, CustomCrystalariumMod/DataLoader.cs, CustomCrystalariumMod/ModConfig.cs, CustomCrystalariumMod/ObjectOverrides.cs, CustomCrystalariumMod/contentPackTemplate/ClonersData.json, CustomCrystalariumMod/i18n/hu.json, CustomCrystalariumMod/integrations/ApiLetter.cs, CustomCrystalariumMod/integrations/GenericModConfigMenuApi.cs, CustomCrystalariumMod/integrations/ILetter.cs, CustomCrystalariumMod/integrations/IMailFrameworkModApi.cs, CustomCrystalariumMod/manifest.json
- Removing MFM dependency
- Adding letter using MFM API.
- New property to enable to crystalarium or cloner to clone every object.
- New property to set the deafult time to clone for undefined object.
- Adds new properties to Config Menu.
- Fix to situations where you could get a cloner or a crystalarium to duplicate items with no wait time by removing it from the ground.
- Change way to create Debris, so it use the same method as the game.
- Hungarian translation.
=> Custom Crystalarium Mod 1.4.0

MailServicesMod/ToolUpgradeOverrides.cs, MailServicesMod/manifest.json
- Only remove the tool from being added to the inventory if it's the trash can. It caused conflict with Animal Husbandry custom tools.
=> Mail Services Mod 1.5.2

ButcherMod/AnimalHusbandryModEntry.cs, ButcherMod/animals/AnimalQueryMenuExtended.cs, ButcherMod/animals/FarmAnimalOverrides.cs, ButcherMod/manifest.json, ButcherMod/tools/FeedingBasketOverrides.cs, ButcherMod/tools/InseminationSyringeOverrides.cs, ButcherMod/tools/MeatCleaverOverrides.cs, ButcherMod/tools/ParticipantRibbonOverrides.cs
- Fix to animal query menu extended not showing the cracker icon when the animal had eaten it.
- Fix to animal query menu extended not respecting showClearBackground option.
- Fix to animals not accepting the cracker after they were pet.
- Some refactoring to Animal Query Menu Extended code
- Fix to producer bonus not being applied
- New transpiler to fix fertility bonus not being applied to layed products.
- Removing old postfix logic that was not working.
- Making the tool validation null safe to avoid bug with other tools. (Afected the StrenghtGame in the stardew valley fair)
=> Animal Husbandry Mod 2.6.8

ProducerFrameworkMod/ContentPack/ProducerConfig.cs, ProducerFrameworkMod/ContentPackTemplate/ProducersConfig.json, ProducerFrameworkMod/Controllers/ProducerController.cs, ProducerFrameworkMod/Controllers/ProducerRuleController.cs, ProducerFrameworkMod/ObjectOverrides.cs, ProducerFrameworkMod/ProducerFrameworkModEntry.cs, ProducerFrameworkMod/manifest.json
- Automate support for vanilla and content patcher machines without needing PFMAutomate
- New property to enable of disable Fairy Dust on machines.
- Support to hoppers
- Fix to Fairy Dust not being applied to PFM machines after SV 1.6
- Fix to avoid loading rules before items.
- Change to some warning messages to user don't report them as bugs.
- PFM now handles removing the item from the inventory after the last stack is consumed. Fix bug were items with 0 stack would be left in the inventory.
- Multiple fixes to fuel consumption.
=> Producer Framework Mod 1.9.0

CustomCrystalariumMod/ClonerController.cs, CustomCrystalariumMod/CustomCloner.cs, CustomCrystalariumMod/CustomCrystalariumMod.csproj, CustomCrystalariumMod/CustomCrystalariumModEntry.cs, CustomCrystalariumMod/DataLoader.cs, CustomCrystalariumMod/ModConfig.cs, CustomCrystalariumMod/ObjectOverrides.cs, CustomCrystalariumMod/contentPackTemplate/ClonersData.json, CustomCrystalariumMod/contentPackTemplate/manifest.json, CustomCrystalariumMod/integrations/GenericModConfigMenuApi.cs, CustomCrystalariumMod/manifest.json
- Update mod to work with Stardew Valley 1.6
- Custom Cloner can now be defined by QualifiedItemId.
- Clonables can now be defined by QualifiedItemId.
- Clonables are now kept by their QualifiedItemId internaly.
- New property KeepQuality. Crystalarium and cloners kept the quality by default before SV 1.6 Don't know if it will be fixed, but this property solves this "bug".
- Updates to .net6
- Patch to keep fairy dust functionality
- Content packs now wait 120 ticks to be loaded the first time.
- Update Generic Mod Config Menu api
- BlockChange nows default to true since that is the vanilla behavior
=> Custom Crystalarium Mod 1.5.0

MailFrameworkMod/ContentPack/Attachment.cs, MailFrameworkMod/ContentPackTemplate/mail.json, MailFrameworkMod/DataLoader.cs, MailFrameworkMod/MailController.cs, MailFrameworkMod/manifest.json
- New property to set the quality of the attachment
- Content pack mails with recipe should now should be redelivered until the recipe is learned.
- Fix warnings about Slingshot
- Fix recipes for craftables been delivered even if the recipe was already learned.
- For legacy reasons, if the recipe id is not found in the learned recipes, it will look for a recipe that create an item with the name of the recipe id.
=> Mail Framework Mod 1.17.0

ButcherMod/AnimalHusbandryMod.csproj, ButcherMod/animals/FarmAnimalExtension.cs, ButcherMod/animals/MeatController.cs, ButcherMod/common/DataLoader.cs, ButcherMod/farmer/FarmerData.cs, ButcherMod/farmer/FarmerLoader.cs, ButcherMod/integrations/GenericModConfigMenuApi.cs, ButcherMod/manifest.json, ButcherMod/tools/ParticipantRibbonOverrides.cs
- Updating dependencies
- Marking deprecated warning on converting code
- Fix null reference when reading modData from farmAnimals
- Fix bug where exchange a shorn sheep would give null reference error.
- Updating to new api of GMCM
=> Animal Husbandry Mod 2.6.10

MailFrameworkMod/DataLoader.cs, MailFrameworkMod/MailController.cs, MailFrameworkMod/manifest.json
- Content pack mails with recipe need to not have attachments for be redelivered if the recipe is not learned.
- Fix cooking recipes with the same logic applied to crafting recipes before.
=> Mail Framework Mod 1.17.1

ProducerFrameworkMod/Api/ProducerFrameworkModApi.cs, ProducerFrameworkMod/Controllers/ProducerController.cs, ProducerFrameworkMod/Controllers/ProducerRuleController.cs, ProducerFrameworkMod/ObjectOverrides.cs, ProducerFrameworkMod/manifest.json
- Fix hopper behavior with vanilla and PFM machines.
- Remove PFM default configuration for some vanilla machines that would cause unexpected behavior.
- Fix mushroom box and log not giving experience as it should if some types of configuration were added to it.
- Mark some craftables with specific behavior as unsupported.
- Fix null reference error when an object with null name was loaded in the game.
=> Producer Framework Mod 1.9.3

ProducerFrameworkMod/Controllers/ProducerRuleController.cs, ProducerFrameworkMod/ObjectOverrides.cs, ProducerFrameworkMod/i18n/fr.json, ProducerFrameworkMod/manifest.json
- Adds French i18n
- Fix machines vanilla machines with ShowNextIndexWhileWorking not show apropriate frame when loading a PFM rule, even if they had no ProducerConfig overriding it
- Fix vanilla machines with ClearContentOvernightCondition not cleating over night if they had a NoInputStartMode configuration.
=> Producer Framework Mod 1.9.4

ButcherMod/AnimalHusbandryModEntry.cs, ButcherMod/ModConfig.cs, ButcherMod/animals/data/AnimalData.cs, ButcherMod/common/DataLoader.cs, ButcherMod/integrations/GenericModConfigMenuApi.cs, ButcherMod/manifest.json, ButcherMod/meats/MeatExtension.cs, ButcherMod/tools/ToolsLoader.cs
- Fix recipe mails not being translated.
- Two new properties to disable the Insemination Syringe and Feeding Basket Letters.
- Fix null reference error when looking for treats and there is an object with null name loaded in the game.
- Update the mod to use GMCM new API.
- Adding the "meat_item" context tag to all meat items.
=> Animal Husbandry Mod 2.6.11

AdvancedWeatherForecastMod/AdvancedWeatherForecastMod.csproj, AdvancedWeatherForecastMod/AdvancedWeatherForecastModEntry.cs, AdvancedWeatherForecastMod/WeatherDataRepository.cs, AdvancedWeatherForecastMod/WeatherForecastController.cs, AdvancedWeatherForecastMod/api/AdvancedWeatherForecastModApi.cs, AdvancedWeatherForecastMod/api/IAdvancedWeatherForecastModApi.cs, AdvancedWeatherForecastMod/common/DataLoader.cs, AdvancedWeatherForecastMod/common/ModConfig.cs, AdvancedWeatherForecastMod/i18n/default.json, AdvancedWeatherForecastMod/i18n/pt.json, AdvancedWeatherForecastMod/integrations/ApiLetter.cs, AdvancedWeatherForecastMod/integrations/GenericModConfigMenuApi.cs, AdvancedWeatherForecastMod/integrations/ILetter.cs, AdvancedWeatherForecastMod/integrations/IMailFrameworkModApi.cs, AdvancedWeatherForecastMod/manifest.json, AdvancedWeatherForecastMod/overrides/BillboardOverrides.cs, AdvancedWeatherForecastMod/overrides/LocationWeatherOverrides.cs, StardewValleyMods.sln
- Shows the weather forecast in the town's calendar and personal calendars.
- You can configure how many days in advance you can see the forecast, from 1 to 27.
- Adds console commands to clear or calculated the forecast. (some randoms are fixed per game, so a rainy day will never become sunny and vice versa)
- Adds API to check and edit future weather, so other mods can integrate with this one.
- Supports Generic Mod Config Menu.
=> Advanced Weather Forecast Mod 1.0.0

ProducerFrameworkMod/ObjectOverrides.cs
This improves compatibility with other mods, namely Extra Machine Config's upcoming feature of allowing non-`Object` input in machines. Currently, if PFM is installed, this prefix detects that `dropInItem` is not an `Object` and skips the rest of the vanilla function, breaking EMC.
=> [PFM] Make a branch in the performObjectDropInAction prefix not skip the vanilla function

EverlastingBaitsUnbreakableTacklesMod/DataLoader.cs
There were two problems. 
The first is that the cache was invalidated BEFORE the changes to ModConfig were saved, causing unpredictable behaviour when enabling/disabling things in settings. 
The second is that the cache was never invalidated at the start, causing recipes to not get registered.
=> Fix Everlasting baits bug
